### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by diarbyrag** [mindpixel-labs/atom-expressionengine#2]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[already-filed]: https://github.com/mindpixel-labs/atom-expressionengine/issues

### Description

Failed to load snippets from '/Users/garybraid/.atom/packages/atom-expressionengine/snippets/categories.cson'

/Users/garybraid/.atom/packages/atom-expressionengine/snippets/categories.cson: Duplicate key 'category_name'

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

[What did you expect to happen?]

**Actual behavior:**

[What actually happened instead?]

**Reproduces how often:**

[What percentage of the time does this happen?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

**Comment by diarbyrag** [comment]
sorry just get the error, not sure how to do all the other things you ask

**Comment by diarbyrag** [comment]
didnt mean to close it D'oh !

**Comment by mindpixel-labs** [comment]
Sorry for the very long delay in response lol. I will be closing this repo or marking it as no longer maintained. I've switched to VScode since then and have a new extension for ExpressionEngine. I'd recommend switching away from Atom as VSCode is much better if you haven't already.
